// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"false","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Chronus","status":true,"description":"ゲーム内時間の導入プラグイン","parameters":{"月ごとの日数配列":"31,28,31,30,31,30,31,31,30,31,30,31","月名配列":"Jan.,Feb.,Mar.,Apr.,May.,Jun.,Jul.,Aug.,Sep.,Oct.,Nov.,Dec.","曜日配列":"(火),(水),(木),(金),(土),(日),(月)","自然時間加算":"5","自然時間加算間隔":"60","場所移動時間加算":"30","戦闘時間加算(固定)":"30","戦闘時間加算(ターン)":"5","年のゲーム変数":"0","月のゲーム変数":"0","日のゲーム変数":"0","曜日IDのゲーム変数":"0","曜日名のゲーム変数":"0","時のゲーム変数":"0","分のゲーム変数":"0","累計時間のゲーム変数":"0","累計日数のゲーム変数":"0","時間帯IDのゲーム変数":"0","天候IDのゲーム変数":"0","フォーマット時間の変数":"0","フォーマット時間の計算式":"HH24 * 60 + MI","日時フォーマット1":"YYYY年 MM月 DD日 DY","日時フォーマット2":"AMHH時 MI分","カレンダー表示X座標":"0","カレンダー表示Y座標":"0","カレンダーフォントサイズ":"0","カレンダー不透明度":"192","カレンダー余白":"8","文字盤画像ファイル":"","長針画像ファイル":"","短針画像ファイル":"","時計X座標":"84","時計Y座標":"156","イベント中時間経過":"false"}},
{"name":"VehiclePassable","status":true,"description":"乗り物通行判定拡張プラグイン","parameters":{"小型船通行リージョン":"1,2,3","小型船通行地形タグ":"1,2,3","小型船不可リージョン":"4,5,6","小型船不可地形タグ":"4,5,6","小型船乗降地形タグ":"","小型船乗降リージョン":"","大型船通行リージョン":"1,2,3","大型船通行地形タグ":"1,2,3","大型船不可リージョン":"4,5,6","大型船不可地形タグ":"4,5,6","大型船乗降地形タグ":"","大型船乗降リージョン":"","飛行船不可リージョン":"4,5,6","飛行船不可地形タグ":"4,5,6","飛行船乗降地形タグ":"","飛行船乗降リージョン":""}},
{"name":"MovieManager","status":true,"description":"動画管理プラグイン","parameters":{}},
{"name":"BootOpeningDemo","status":false,"description":"タイトル画面を出す前にオープニングデモから開始します","parameters":{"firstMapId":"3","startX":"0","startY":"0"}},
{"name":"TitleCommandPosition","status":true,"description":"タイトルコマンドウィンドウの位置を変更します。","parameters":{"Offset X":"-190","Offset Y":"-120","Width":"100","Background":"0"}},
{"name":"use_DI_Joypad_ver_1_2","status":true,"description":"DirectInput方式のジョイパッドが使えるようになります","parameters":{"alert":"リロードを実行します。ゲームパッドを使用している場合、パッドの接続が途切れることがあります。"}},
{"name":"ExcludeStatus","status":true,"description":"指定したステータス項目を、ステータス画面と装備画面に表示しないようにします。","parameters":{"Exclude Status":"1,2,3,4,5"}}
];
